export const US_CITIES = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "Austin, TX",
  "Jacksonville, FL",
  "Fort Worth, TX",
  "San Jose, CA",
  "Columbus, OH",
  "Charlotte, NC",
  "Indianapolis, IN",
  "San Francisco, CA",
  "Seattle, WA",
  "Denver, CO",
  "Oklahoma City, OK",
  "Nashville, TN",
  "El Paso, TX",
  "Washington, DC",
  "Boston, MA",
  "Las Vegas, NV",
  "Portland, OR",
  "Detroit, MI",
  "Memphis, TN",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Sacramento, CA",
  "Mesa, AZ",
  "Kansas City, MO",
  "Atlanta, GA",
  "Omaha, NE",
  "Colorado Springs, CO",
  "Raleigh, NC",
  "Long Beach, CA",
  "Virginia Beach, VA",
  "Miami, FL",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tulsa, OK",
  "Tampa, FL",
  "Arlington, TX",
  "New Orleans, LA",
  "Wichita, KS",
  "Cleveland, OH",
  "Bakersfield, CA",
  "Aurora, CO",
  "Anaheim, CA",
  "Honolulu, HI",
  "Santa Ana, CA",
  "Riverside, CA",
  "Corpus Christi, TX",
  "Lexington, KY",
  "Stockton, CA",
  "Henderson, NV",
  "Saint Paul, MN",
  "St. Louis, MO",
  "Cincinnati, OH",
  "Pittsburgh, PA",
  "Greensboro, NC",
  "Anchorage, AK",
  "Plano, TX",
  "Lincoln, NE",
  "Orlando, FL",
  "Irvine, CA",
  "Newark, NJ",
  "Toledo, OH",
  "Durham, NC",
  "Chula Vista, CA",
  "Fort Wayne, IN",
  "Jersey City, NJ",
  "St. Petersburg, FL",
  "Laredo, TX",
  "Madison, WI",
  "Chandler, AZ",
  "Buffalo, NY",
  "Lubbock, TX",
  "Scottsdale, AZ",
  "Reno, NV",
  "Glendale, AZ",
  "Gilbert, AZ",
  "Winston-Salem, NC",
  "North Las Vegas, NV",
  "Norfolk, VA",
  "Chesapeake, VA",
  "Garland, TX",
  "Irving, TX",
  "Hialeah, FL",
  "Fremont, CA",
  "Boise, ID",
  "Richmond, VA",
  "Baton Rouge, LA",
  "Spokane, WA",
  "Des Moines, IA",
  "Tacoma, WA",
  "San Bernardino, CA",
  "Modesto, CA",
  "Fontana, CA",
  "Santa Clarita, CA",
  "Birmingham, AL",
  "Rochester, NY",
  "Fayetteville, NC",
  "Oxnard, CA",
  "Moreno Valley, CA",
  "Fort Lauderdale, FL",
  "Huntington Beach, CA",
  "Yonkers, NY",
  "Glendale, CA",
  "Amarillo, TX",
  "Montgomery, AL",
  "McKinney, TX",
  "Akron, OH",
  "Little Rock, AR",
  "Grand Rapids, MI",
  "Salt Lake City, UT",
  "Huntsville, AL",
  "Providence, RI",
  "Knoxville, TN",
  "Worcester, MA",
  "Newport News, VA",
  "Brownsville, TX",
  "Santa Rosa, CA",
  "Overland Park, KS",
  "Tempe, AZ",
  "Grand Prairie, TX",
  "Cape Coral, FL",
  "Sioux Falls, SD",
  "Ontario, CA",
  "Chattanooga, TN",
  "Vancouver, WA",
  "Elk Grove, CA",
  "Fort Collins, CO",
  "Springfield, MO",
  "Pembroke Pines, FL",
  "Corona, CA",
  "Eugene, OR",
  "Salem, OR",
  "Pasadena, TX",
  "Rockford, IL",
  "Cary, NC",
  "Palmdale, CA",
  "Hayward, CA",
  "Alexandria, VA",
  "Lancaster, CA",
  "Salinas, CA",
  "Kansas City, KS",
  "Sunnyvale, CA",
  "Hollywood, FL",
  "Killeen, TX",
  "Torrance, CA",
  "Bridgeport, CT",
  "Escondido, CA",
  "Pasadena, CA",
  "Naperville, IL",
  "Mesquite, TX",
  "Savannah, GA",
  "Syracuse, NY",
  "McAllen, TX",
  "Orange, CA",
  "Fullerton, CA",
  "Charleston, SC",
  "Pomona, CA",
  "Dayton, OH",
  "Hampton, VA",
  "Naples, FL",
  "Asheville, NC",
  "Aurora, IL",
  "Cedar Rapids, IA",
  "Elizabeth, NJ",
  "Columbia, SC",
  "New Haven, CT",
  "Miami Gardens, FL",
  "Stamford, CT",
  "Concord, CA",
  "Hartford, CT",
  "Kissimmee, FL",
  "Manchester, NH",
  "Allentown, PA",
  "West Palm Beach, FL",
  "Wilmington, NC",
  "Kent, WA",
  "Provo, UT",
  "Clearwater, FL",
];
